apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pipeline-videos
  description: Videos used by pipeline-docs
  annotations: 
    github.com/project-slug: BESTSELLER/pipeline-videos
spec:
  type: library
  lifecycle: production
  owner: engineering-services
  dependsOn:
    - component:default/pipeline-docs
